# Generated by Django 3.2.7 on 2021-09-18 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('date_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вопрос с выбором ответа',
                'verbose_name_plural': 'Вопросы с выбором ответа',
            },
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('date_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вопрос ответ текстом',
                'verbose_name_plural': 'Вопросы ответ текстом',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questiontext')),
            ],
            options={
                'verbose_name': 'Ответ текстом',
                'verbose_name_plural': 'Ответы текстом',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(blank=True, default=False, verbose_name='')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('votes', models.IntegerField(default=0, verbose_name='Голосов')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
